openapi: 3.0.2
info:
  version: 1.0.0
  title: Transmate APIs
  termsOfService: "https://www.transmate.eu/legal/terms-of-use"
  contact:
    email: info@transmate.eu
    url: "https://www.transmate.eu/contact-us"
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://uploads-ssl.webflow.com/5bb09c94c110e4695b7fbe87/5bb0cfa5ace69ce819b42b1a_571d49bb558170fc61afe2ec_logo_large_new_transmate.png"
  description: >
    description of the apis of transmate

    # Introduction

    Transmate has multiple api available
    sea distance api is one of them

    ## Sea distance
    
    use this api to get estimated miles and leadtimes for port to port routes
    leadtimes is an estimated lead time for container traffic, 
    to get an estimated travel time you can divide the distance by the speed of the vessel (something between 10 and 20 knots)

externalDocs:
  description: Transmate Webiste
  url: "https://www.transmate.eu/"

servers:
  - url: "https://eu-de.functions.appdomain.cloud/api/v1/web/e53db790-412a-497a-aec2-85c02104d6a6"
paths:
  /seaDistance:
    get:
      summary: Returns the sea distance between two ports.
      security:
        - api_key: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '../transmateSchemas/restAPI/sea-distance.json'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        '404':
          description: Not Found

      operationId: getSeadistance
      x-openwhisk:
        namespace: e53db790-412a-497a-aec2-85c02104d6a6
        action: seaDistance
        package: importFunctions
        url: "https://eu-de.functions.appdomain.cloud/api/v1/web/e53db790-412a-497a-aec2-85c02104d6a6/importFunctions/seaDistance.json"

components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: apiKey
      description: must be in header of request

  schemas:
    ErrorResponse:
      description: Container object for one or more errors returned by the API.
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

    Error:
      description: An error object returned by the API.
      type: object
      required:
        - status
        - title
      properties:
        status:
          type: string
          description: The HTTP status code applicable to this problem expressed as a string
          example: 400
        title:
          type: string
          description: Short human-readable summary of the problem
          example: Bad Request
        detail:
          type: string
          description: Optional longer form human-readable explanation tailored to be specific to this specific occurence of the problem.
        source:
          type: object
          properties:
            pointer:
              type: string
              description: A string containing a JSON pointer to the specific field within a received JSON body that caused the problem, e.g. '/data/attributes/title' to refer to the `title` property within the `attributes` object that is a child of the top level `data` object.
              example: /data/attributes/title
            parameter:
              type: string
              description: A string containing a reference to a specific query parameter that has caused the problem.
              example: long
